import os
from datetime import datetime, timezone, timedelta

from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

GOAL = 1_000_000
MOSCOW = timezone(timedelta(hours=3))

_pool: ConnectionPool | None = None


def _get_pool() -> ConnectionPool:
    global _pool
    if _pool is None:
        _pool = ConnectionPool(
            os.environ["DATABASE_URL"],
            kwargs={"row_factory": dict_row},
        )
    return _pool


def get_connection():
    """Context manager yielding a pooled connection; commits on a clean exit,
    rolls back on exception, then returns the connection to the pool."""
    return _get_pool().connection()


def init_db() -> None:
    with get_connection() as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS beers (
                user_id        BIGINT NOT NULL,
                username       TEXT,
                full_name      TEXT,
                count          INTEGER NOT NULL DEFAULT 0,
                last_video_at  TEXT,
                current_streak INTEGER NOT NULL DEFAULT 0,
                longest_streak INTEGER NOT NULL DEFAULT 0,
                PRIMARY KEY (user_id)
            )
        """)

        conn.execute("""
            CREATE TABLE IF NOT EXISTS video_log (
                id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id    BIGINT NOT NULL,
                chat_id    BIGINT NOT NULL,
                sent_at    TEXT NOT NULL,
                message_id BIGINT,
                file_id    TEXT
            )
        """)
        # migration: older rows predate the montage feature and lack file_id
        conn.execute("ALTER TABLE video_log ADD COLUMN IF NOT EXISTS file_id TEXT")
        # partial unique index: prevents duplicate message processing on bot restart
        conn.execute("""
            CREATE UNIQUE INDEX IF NOT EXISTS uq_video_log_msg
            ON video_log(chat_id, message_id)
            WHERE message_id IS NOT NULL
        """)
        # composite index for fast date-range queries per chat
        conn.execute("""
            CREATE INDEX IF NOT EXISTS idx_video_log_chat_sent
            ON video_log(chat_id, sent_at)
        """)
        # index for cross-chat sent_at range (get_videos_last_n_days)
        conn.execute("""
            CREATE INDEX IF NOT EXISTS idx_video_log_sent
            ON video_log(sent_at)
        """)

        conn.execute("""
            CREATE TABLE IF NOT EXISTS settings (
                key   TEXT PRIMARY KEY,
                value TEXT NOT NULL
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS text_messages (
                chat_id    BIGINT NOT NULL,
                message_id BIGINT NOT NULL,
                sent_at    TEXT,
                PRIMARY KEY (chat_id, message_id)
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS mvp_log (
                date    TEXT PRIMARY KEY,
                user_id BIGINT NOT NULL,
                chat_id BIGINT NOT NULL
            )
        """)

    _validate_video_log_integrity()


def _validate_video_log_integrity() -> None:
    """Warn at startup if video_log contains duplicate (chat_id, message_id) pairs."""
    with get_connection() as conn:
        dups = conn.execute("""
            SELECT chat_id, message_id, COUNT(*) AS cnt
            FROM video_log
            WHERE message_id IS NOT NULL
            GROUP BY chat_id, message_id
            HAVING COUNT(*) > 1
        """).fetchall()
    if dups:
        import logging
        log = logging.getLogger(__name__)
        log.warning(
            "video_log integrity issue: %d duplicate (chat_id, message_id) pair(s) found. "
            "Use /remove to clean them up.",
            len(dups),
        )
        for d in dups:
            log.warning("  chat_id=%s message_id=%s count=%s", d["chat_id"], d["message_id"], d["cnt"])


# ── Video counting ──────────────────────────────────────────────────────────

def add_beer(
    user_id: int,
    username: str | None,
    full_name: str,
    chat_id: int,
    message_id: int | None = None,
    file_id: str | None = None,
) -> tuple[int, int, bool, int]:
    """Increment count, log the video, return (user_count, total_count, added, current_streak).

    added=False when message_id is already in video_log (duplicate delivery on restart).
    In that case beers.count is NOT changed.

    file_id is the video_note's Telegram file_id, stored so the nightly montage
    job can re-download the clip later.
    """
    now = datetime.now(MOSCOW).isoformat()
    with get_connection() as conn:
        # Try to record the video first; ON CONFLICT DO NOTHING silently skips known message_ids.
        cur = conn.execute(
            """
            INSERT INTO video_log (user_id, chat_id, sent_at, message_id, file_id)
            VALUES (%s, %s, %s, %s, %s)
            ON CONFLICT (chat_id, message_id) WHERE message_id IS NOT NULL DO NOTHING
            """,
            (user_id, chat_id, now, message_id, file_id),
        )
        added = cur.rowcount == 1

        if not added:
            # Duplicate — return current counts unchanged.
            row = conn.execute(
                "SELECT count, current_streak FROM beers WHERE user_id = %s", (user_id,)
            ).fetchone()
            user_count = row["count"] if row else 0
            streak = row["current_streak"] if row else 0
            total = conn.execute("SELECT COALESCE(SUM(count), 0) AS t FROM beers").fetchone()["t"]
            return user_count, total, False, streak

        # Calculate streak before upserting
        today = datetime.now(MOSCOW).date()
        existing = conn.execute(
            "SELECT last_video_at, current_streak, longest_streak FROM beers WHERE user_id = %s",
            (user_id,),
        ).fetchone()

        if existing and existing["last_video_at"]:
            last_date = datetime.fromisoformat(existing["last_video_at"]).date()
            delta = (today - last_date).days
            if delta == 0:
                # Already sent one today — keep streak
                new_streak = existing["current_streak"]
            elif delta == 1:
                # Consecutive day — extend streak
                new_streak = existing["current_streak"] + 1
            else:
                # Gap — reset
                new_streak = 1
        else:
            new_streak = 1

        new_longest = max(new_streak, existing["longest_streak"] if existing else 0)

        conn.execute("""
            INSERT INTO beers (user_id, username, full_name, count, last_video_at,
                               current_streak, longest_streak)
            VALUES (%s, %s, %s, 1, %s, %s, %s)
            ON CONFLICT(user_id) DO UPDATE SET
                username       = excluded.username,
                full_name      = excluded.full_name,
                count          = beers.count + 1,
                last_video_at  = excluded.last_video_at,
                current_streak = excluded.current_streak,
                longest_streak = excluded.longest_streak
        """, (user_id, username, full_name, now, new_streak, new_longest))
        user_count = conn.execute(
            "SELECT count FROM beers WHERE user_id = %s", (user_id,)
        ).fetchone()["count"]
        total = conn.execute("SELECT COALESCE(SUM(count), 0) AS t FROM beers").fetchone()["t"]
        return user_count, total, True, new_streak


def remove_video_log_cascade(ids: list[int]) -> tuple[list[int], list[tuple[int, str, int]]]:
    """
    Delete video_log rows by id and subtract from each user's count in beers.

    Returns:
        removed  — list of ids actually deleted
        affected — list of (user_id, full_name, delta) for each user whose count changed
    """
    if not ids:
        return [], []
    placeholders = ",".join(["%s"] * len(ids))
    with get_connection() as conn:
        # Find rows that exist
        rows = conn.execute(
            f"SELECT id, user_id FROM video_log WHERE id IN ({placeholders})", ids
        ).fetchall()
        if not rows:
            return [], []

        # Count how many to subtract per user
        from collections import Counter
        delta_by_user: Counter = Counter(r["user_id"] for r in rows)
        removed_ids = [r["id"] for r in rows]

        conn.execute(f"DELETE FROM video_log WHERE id IN ({placeholders})", ids)

        affected = []
        for user_id, delta in delta_by_user.items():
            conn.execute(
                "UPDATE beers SET count = GREATEST(0, count - %s) WHERE user_id = %s",
                (delta, user_id),
            )
            name_row = conn.execute("SELECT full_name FROM beers WHERE user_id = %s", (user_id,)).fetchone()
            name = name_row["full_name"] if name_row else str(user_id)
            affected.append((user_id, name, delta))

    return removed_ids, affected


def get_total_count() -> int:
    with get_connection() as conn:
        return conn.execute(
            "SELECT COALESCE(SUM(count), 0) AS t FROM beers"
        ).fetchone()["t"]


def get_today_count(chat_id: int) -> int:
    """Count circle videos sent today (Moscow date) in this chat."""
    today = datetime.now(MOSCOW).date().isoformat()
    with get_connection() as conn:
        row = conn.execute("""
            SELECT COUNT(*) AS c FROM video_log
            WHERE chat_id = %s AND substr(sent_at, 1, 10) = %s
        """, (chat_id, today)).fetchone()
        return row["c"]


def get_date_count(chat_id: int, date_str: str) -> int:
    """Count circle videos for a specific date (YYYY-MM-DD) in this chat."""
    from datetime import date as _date
    next_day = (_date.fromisoformat(date_str) + timedelta(days=1)).isoformat()
    with get_connection() as conn:
        row = conn.execute("""
            SELECT COUNT(*) AS c FROM video_log
            WHERE chat_id = %s AND sent_at >= %s AND sent_at < %s
        """, (chat_id, date_str, next_day)).fetchone()
        return row["c"]


def get_video_file_ids_for_date(chat_id: int, date_str: str) -> list[str]:
    """Return file_ids of circle videos sent on date_str (YYYY-MM-DD) in this chat,
    oldest first. Rows without a stored file_id (legacy data, sent before the
    montage feature, or restored from a chat export) are skipped."""
    from datetime import date as _date
    next_day = (_date.fromisoformat(date_str) + timedelta(days=1)).isoformat()
    with get_connection() as conn:
        rows = conn.execute("""
            SELECT file_id FROM video_log
            WHERE chat_id = %s AND sent_at >= %s AND sent_at < %s AND file_id IS NOT NULL
            ORDER BY sent_at ASC
        """, (chat_id, date_str, next_day)).fetchall()
    return [r["file_id"] for r in rows]


def get_videos_last_n_days(n: int = 5) -> int:
    """Total circle videos logged across all chats in the last n days."""
    cutoff = (datetime.now(MOSCOW) - timedelta(days=n)).isoformat()
    with get_connection() as conn:
        row = conn.execute(
            "SELECT COUNT(*) AS c FROM video_log WHERE sent_at >= %s",
            (cutoff,)
        ).fetchone()
        return row["c"]


def get_top_drinkers_for_date(chat_id: int, date_str: str, limit: int = 3) -> list[dict]:
    """Top drinkers for a specific date (YYYY-MM-DD), joined with full_name from beers.

    Ties on day_count go to whoever reached that count first — the earliest
    final circle of the day. That's who the daily MVP is awarded to."""
    from datetime import date as _date
    next_day = (_date.fromisoformat(date_str) + timedelta(days=1)).isoformat()
    with get_connection() as conn:
        return conn.execute("""
            SELECT v.user_id, b.full_name, COUNT(*) AS day_count,
                   MAX(v.sent_at) AS last_beer_at
            FROM video_log v
            JOIN beers b ON b.user_id = v.user_id
            WHERE v.chat_id = %s AND v.sent_at >= %s AND v.sent_at < %s
            GROUP BY v.user_id, b.full_name
            ORDER BY day_count DESC, last_beer_at ASC, v.user_id ASC
            LIMIT %s
        """, (chat_id, date_str, next_day, limit)).fetchall()


def get_leaderboard(limit: int | None = 10) -> list[dict]:
    """Users with count > 0, ranked by count then — on a tie — by whoever
    reached that count first (earliest last circle).
    limit=None returns the whole table (used by /none)."""
    query = """
        SELECT user_id, full_name, username, count, current_streak, longest_streak
        FROM beers
        WHERE count > 0
        ORDER BY count DESC, last_video_at IS NULL, last_video_at ASC
    """
    with get_connection() as conn:
        if limit is None:
            return conn.execute(query).fetchall()
        return conn.execute(query + " LIMIT %s", (limit,)).fetchall()


def track_member(user_id: int, username: str | None, full_name: str) -> None:
    """Add a user to the DB if not already known (so they appear in risk zone)."""
    with get_connection() as conn:
        conn.execute("""
            INSERT INTO beers (user_id, username, full_name, count)
            VALUES (%s, %s, %s, 0)
            ON CONFLICT (user_id) DO NOTHING
        """, (user_id, username, full_name))
        conn.execute("""
            UPDATE beers SET username = %s, full_name = %s WHERE user_id = %s
        """, (username, full_name, user_id))


def get_inactive_users(days: int = 20) -> list[dict]:
    """
    Users who:
    - have never sent a circle video (count = 0), OR
    - have a known last_video_at that is older than `days` days.
    Users with count > 0 but NULL last_video_at are legacy records (videos sent
    before timestamp tracking) — we exclude them to avoid false positives.
    """
    cutoff = (datetime.now(MOSCOW) - timedelta(days=days)).isoformat()
    with get_connection() as conn:
        return conn.execute("""
            SELECT full_name, username, count, last_video_at
            FROM beers
            WHERE
                count = 0
                OR (last_video_at IS NOT NULL AND last_video_at < %s)
            ORDER BY last_video_at ASC NULLS FIRST
        """, (cutoff,)).fetchall()


def get_count(user_id: int) -> int:
    with get_connection() as conn:
        row = conn.execute(
            "SELECT count FROM beers WHERE user_id = %s", (user_id,)
        ).fetchone()
        return row["count"] if row else 0


def reset_count(user_id: int) -> None:
    with get_connection() as conn:
        conn.execute("UPDATE beers SET count = 0 WHERE user_id = %s", (user_id,))


# ── MVP tracking ───────────────────────────────────────────────────────────

def record_mvp(date_str: str, user_id: int, chat_id: int) -> None:
    """Record the day's MVP (top drinker). Safe to call multiple times — overwrites."""
    with get_connection() as conn:
        conn.execute("""
            INSERT INTO mvp_log (date, user_id, chat_id) VALUES (%s, %s, %s)
            ON CONFLICT (date) DO UPDATE SET
                user_id = excluded.user_id,
                chat_id = excluded.chat_id
        """, (date_str, user_id, chat_id))


def get_mvp_counts() -> dict[int, int]:
    """Return {user_id: total_mvp_wins} for all users who have won at least once."""
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT user_id, COUNT(*) AS wins FROM mvp_log GROUP BY user_id"
        ).fetchall()
    return {r["user_id"]: r["wins"] for r in rows}


def get_mvp_streak() -> tuple[int | None, int]:
    """
    Return (user_id, streak_length) for the user holding the current winning streak.
    streak_length=0 means no MVPs recorded yet.
    """
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT date, user_id FROM mvp_log ORDER BY date DESC"
        ).fetchall()
    if not rows:
        return None, 0
    leader_id = rows[0]["user_id"]
    # Count consecutive MVP days from the most recent, held by the same user.
    streak = 0
    for r in rows:
        if r["user_id"] == leader_id:
            streak += 1
        else:
            break
    return leader_id, streak


def get_user_rank(user_id: int) -> int:
    """Return the user's all-time rank by count (1 = best). 0 if not found."""
    with get_connection() as conn:
        row = conn.execute("""
            SELECT COUNT(*) + 1 AS rank
            FROM beers
            WHERE count > (SELECT count FROM beers WHERE user_id = %s)
        """, (user_id,)).fetchone()
    return row["rank"] if row else 0


def get_pivot_score() -> float:
    """
    Composite score for each user = count + mvp_wins*50 + longest_streak*10.
    Returns the average of that score across all users with count > 0.
    Returns 0 if no users.
    """
    with get_connection() as conn:
        rows = conn.execute("""
            SELECT b.user_id,
                   b.count,
                   b.longest_streak,
                   COALESCE(m.wins, 0) AS mvp_wins
            FROM beers b
            LEFT JOIN (
                SELECT user_id, COUNT(*) AS wins FROM mvp_log GROUP BY user_id
            ) m ON m.user_id = b.user_id
            WHERE b.count > 0
        """).fetchall()
    if not rows:
        return 0.0
    scores = [r["count"] + r["mvp_wins"] * 50 + r["longest_streak"] * 10 for r in rows]
    return sum(scores) / len(scores)


def get_user_composite_score(user_id: int) -> float:
    """Composite score for a single user."""
    with get_connection() as conn:
        row = conn.execute("""
            SELECT b.count, b.longest_streak,
                   COALESCE(m.wins, 0) AS mvp_wins
            FROM beers b
            LEFT JOIN (
                SELECT user_id, COUNT(*) AS wins FROM mvp_log GROUP BY user_id
            ) m ON m.user_id = b.user_id
            WHERE b.user_id = %s
        """, (user_id,)).fetchone()
    if not row:
        return 0.0
    return row["count"] + row["mvp_wins"] * 50 + row["longest_streak"] * 10


def get_streak(user_id: int) -> tuple[int, int]:
    """Return (current_streak, longest_streak) for a user."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT current_streak, longest_streak FROM beers WHERE user_id = %s", (user_id,)
        ).fetchone()
    return (row["current_streak"], row["longest_streak"]) if row else (0, 0)


def get_users_on_streak(min_days: int = 3) -> list[dict]:
    """Users whose current_streak >= min_days, ordered by streak desc."""
    with get_connection() as conn:
        return conn.execute("""
            SELECT user_id, full_name, current_streak, longest_streak
            FROM beers
            WHERE current_streak >= %s
            ORDER BY current_streak DESC
        """, (min_days,)).fetchall()


def get_current_streak_leaderboard(limit: int = 20) -> list[dict]:
    """Users with an active streak, ranked by current_streak desc.
    Ties go to whoever has been on the streak longer (earlier last circle)."""
    with get_connection() as conn:
        return conn.execute("""
            SELECT user_id, full_name, current_streak, longest_streak
            FROM beers
            WHERE current_streak > 0
            ORDER BY current_streak DESC, last_video_at ASC
            LIMIT %s
        """, (limit,)).fetchall()


def get_longest_streak_leaderboard(limit: int = 20) -> list[dict]:
    """All-time record streaks, ranked by longest_streak desc."""
    with get_connection() as conn:
        return conn.execute("""
            SELECT user_id, full_name, current_streak, longest_streak
            FROM beers
            WHERE longest_streak > 0
            ORDER BY longest_streak DESC, full_name ASC
            LIMIT %s
        """, (limit,)).fetchall()


def expire_stale_streaks() -> int:
    """Zero out current_streak for anyone who didn't send a circle "yesterday"
    (the day that just ended). Without this, a broken streak just sits in the
    DB at its old value — unchanged since add_beer() only ever recalculates it
    lazily, on that user's *next* video — so leaderboards and /stats would keep
    showing a dead streak as still alive until the user happens to drink again.
    Run once daily at 00:00 Moscow time, right after the day rolls over, so the
    streak is exact from the first read of the new day.
    Returns the number of users reset."""
    yesterday = (datetime.now(MOSCOW).date() - timedelta(days=1)).isoformat()
    with get_connection() as conn:
        cur = conn.execute("""
            UPDATE beers
            SET current_streak = 0
            WHERE current_streak > 0
              AND (last_video_at IS NULL OR substr(last_video_at, 1, 10) < %s)
        """, (yesterday,))
        return cur.rowcount


def get_mvp_wins(user_id: int) -> int:
    """Return total MVP wins for a single user."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT COUNT(*) AS wins FROM mvp_log WHERE user_id = %s", (user_id,)
        ).fetchone()
    return row["wins"]


# ── Settings (stores group chat_id for daily report) ───────────────────────

_chat_id_cache: int | None = None


def save_chat_id(chat_id: int) -> None:
    """Persist the main group's chat_id. No-op once it's already stored, so this
    can be called on every circle without a write per message."""
    global _chat_id_cache
    if _chat_id_cache == chat_id:
        return
    with get_connection() as conn:
        conn.execute("""
            INSERT INTO settings (key, value) VALUES ('chat_id', %s)
            ON CONFLICT (key) DO UPDATE SET value = excluded.value
        """, (str(chat_id),))
    _chat_id_cache = chat_id


def get_chat_id() -> int | None:
    global _chat_id_cache
    if _chat_id_cache is not None:
        return _chat_id_cache
    with get_connection() as conn:
        row = conn.execute(
            "SELECT value FROM settings WHERE key = 'chat_id'"
        ).fetchone()
    _chat_id_cache = int(row["value"]) if row else None
    return _chat_id_cache


def save_setting(key: str, value: str) -> None:
    with get_connection() as conn:
        conn.execute("""
            INSERT INTO settings (key, value) VALUES (%s, %s)
            ON CONFLICT (key) DO UPDATE SET value = excluded.value
        """, (key, value))


def get_setting(key: str) -> str | None:
    with get_connection() as conn:
        row = conn.execute(
            "SELECT value FROM settings WHERE key = %s", (key,)
        ).fetchone()
        return row["value"] if row else None


# ── Text message tracking (for /clean) ────────────────────────────────────

def track_text_message(chat_id: int, message_id: int) -> None:
    now = datetime.now(MOSCOW).isoformat()
    with get_connection() as conn:
        conn.execute("""
            INSERT INTO text_messages (chat_id, message_id, sent_at) VALUES (%s, %s, %s)
            ON CONFLICT (chat_id, message_id) DO NOTHING
        """, (chat_id, message_id, now))


def get_text_message_ids(chat_id: int) -> list[int]:
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT message_id FROM text_messages WHERE chat_id = %s", (chat_id,)
        ).fetchall()
        return [r["message_id"] for r in rows]


def get_text_message_ids_for_date(chat_id: int, date_str: str) -> list[int]:
    """Return message_ids for a specific date (YYYY-MM-DD)."""
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT message_id FROM text_messages WHERE chat_id = %s AND substr(sent_at,1,10) = %s",
            (chat_id, date_str),
        ).fetchall()
        return [r["message_id"] for r in rows]


def clear_text_messages(chat_id: int) -> None:
    with get_connection() as conn:
        conn.execute("DELETE FROM text_messages WHERE chat_id = %s", (chat_id,))


def clear_text_messages_for_date(chat_id: int, date_str: str) -> None:
    with get_connection() as conn:
        conn.execute(
            "DELETE FROM text_messages WHERE chat_id = %s AND substr(sent_at,1,10) = %s",
            (chat_id, date_str),
        )


# ── Period leaderboards ────────────────────────────────────────────────────

def get_leaderboard_for_period(chat_id: int, since: str, limit: int = 20) -> list[dict]:
    """
    Top drinkers since `since` (ISO date string, inclusive) in the given chat.
    Ties on the period count go to whoever reached it first — the earliest
    final circle in the window. Only users with at least 1 circle are returned.
    """
    with get_connection() as conn:
        return conn.execute("""
            SELECT v.user_id, b.full_name, COUNT(*) AS period_count,
                   MAX(v.sent_at) AS last_beer_at
            FROM video_log v
            JOIN beers b ON b.user_id = v.user_id
            WHERE v.chat_id = %s
              AND v.sent_at >= %s
            GROUP BY v.user_id, b.full_name
            ORDER BY period_count DESC, last_beer_at ASC
            LIMIT %s
        """, (chat_id, since, limit)).fetchall()


def get_period_count(chat_id: int, since: str) -> int:
    """Total circle videos since `since` (ISO date string, inclusive) in the given chat."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT COUNT(*) AS c FROM video_log WHERE chat_id = %s AND sent_at >= %s",
            (chat_id, since),
        ).fetchone()
        return row["c"]


# ── Removal helpers ───────────────────────────────────────────────────────

def find_user_by_username(username: str) -> dict | None:
    """Look up a user by @username (with or without the @). Case-insensitive."""
    username = username.lstrip("@")
    with get_connection() as conn:
        return conn.execute(
            "SELECT user_id, full_name, username FROM beers WHERE LOWER(username) = LOWER(%s)",
            (username,),
        ).fetchone()


def get_last_n_video_ids(user_id: int, n: int) -> list[int]:
    """Return the IDs of the N most recent video_log rows for a user."""
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT id FROM video_log WHERE user_id = %s ORDER BY id DESC LIMIT %s",
            (user_id, n),
        ).fetchall()
    return [r["id"] for r in rows]


# ── Weekly chart data ──────────────────────────────────────────────────────

def get_daily_counts(chat_id: int, days: int = 7) -> list[tuple[str, int]]:
    """Return [(date_str, count), ...] for the last `days` days, sorted ascending."""
    today = datetime.now(MOSCOW).date()
    since = (today - timedelta(days=days - 1)).isoformat()
    with get_connection() as conn:
        rows = conn.execute("""
            SELECT substr(sent_at, 1, 10) AS day, COUNT(*) AS c
            FROM video_log
            WHERE chat_id = %s AND sent_at >= %s
            GROUP BY day
            ORDER BY day
        """, (chat_id, since)).fetchall()
    counts = {r["day"]: r["c"] for r in rows}
    # Ensure every day in the window is present, filling gaps with 0
    return [
        ((today - timedelta(days=i)).isoformat(),
         counts.get((today - timedelta(days=i)).isoformat(), 0))
        for i in range(days - 1, -1, -1)
    ]
